# -*- coding: utf-8 -*-
"""IndiaBudget2024Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MsOrQdRU1TtmQmYzDGZ0hk7h2_uFPiBb
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_excel("/content/india budget.xlsx")
data.head()

print(data)

null_values = data.isnull().sum()
print(null_values)

# Basic statistics
summary_stats = data.describe()

summary_stats

"""Count: 55 ministries/departments"""

# Top 10 ministries by budget allocation
top_10_ministries = data.nlargest(10, 'Total')

top_10_ministries

# Visualization: Top 10 ministries by budget allocation
plt.figure(figsize=(12, 8))
plt.barh(top_10_ministries['Name of Ministry'], top_10_ministries['Total'], color='skyblue')
plt.xlabel('Budget Allocation (in crores)')
plt.title('Top 10 Ministries by Budget Allocation')
plt.gca().invert_yaxis()
plt.show()

"""Mean Budget Allocation: ₹86,649.17 crores
Standard Deviation: ₹264,082.30 crores
Min Budget Allocation: ₹192.55 crores
Max Budget Allocation: ₹1,850,229.87 crores
Median Budget Allocation: ₹10,404.63 crores

The budget allocation data presents a significant spread and a few key observations can be made from the given statistics:

1. **High Standard Deviation**:
   The standard deviation is ₹264,082.30 crores, which is much larger than the mean of ₹86,649.17 crores. This indicates a high variability in budget allocations, suggesting that some allocations are extremely high compared to others.

2. **Extremely Wide Range**:
   The range, calculated as the difference between the maximum (₹1,850,229.87 crores) and minimum (₹192.55 crores) budget allocations, is ₹1,850,037.32 crores. This wide range further supports the presence of significant disparities among budget allocations.

3. **Mean vs. Median**:
   The mean budget allocation is ₹86,649.17 crores, while the median is much lower at ₹10,404.63 crores. This substantial difference indicates a right-skewed distribution, where a few very large allocations are inflating the mean.

4. **Outliers**:
   Given the high maximum value compared to the mean and median, it is likely that there are outliers (very high budget allocations) that are influencing the average. These outliers could be specific sectors or projects that receive significantly more funding than others.

5. **Skewness**:
   The data is likely skewed to the right (positively skewed), meaning that most of the budget allocations are concentrated at the lower end, with a few very high values pulling the mean to the right.

### Conclusion
The analysis of the budget allocation data reveals a high degree of variability and the presence of outliers. The significant difference between the mean and median, along with the high standard deviation and wide range, suggests that while most budget allocations are relatively low, a few allocations are extremely high, leading to a skewed distribution. This implies that in the context of budget allocation, a small number of sectors or projects receive a disproportionately large amount of funding compared to the rest.
"""

df = top_10_ministries["Total"]
labels = top_10_ministries["Name of Ministry"]
plt.figure(figsize=(7,7))
plt.pie(df, labels=labels, autopct='%1.1f%%', startangle=90, pctdistance=0.85, shadow =True)
central_circle = plt.Circle((0, 0), 0.5, color='white')
fig = plt.gcf()
fig.gca().add_artist(central_circle)
plt.rc('font', size=12)
plt.title("Distribution of The Budget", fontsize=20)
plt.show()

"""We can see that the finance department is getting 45.9% of the funds

This suggests a major focus on financial management, budgeting, and economic policies.

Followed by
Ministry of Defence: With 15.4%, this indicates substantial investment in defense-related activities and security.

Ministry of Road Transport and Highways:6.9% shows a significant allocation towards infrastructure development, specifically roads and highways.

Ministry of Railways:6.3% indicates a considerable amount for railway infrastructure and services.

### **Overall Government Strategy:**

1. **Focus on Economic Management**: The substantial investment in the Ministry of Finance indicates the government’s commitment to fostering a stable and growth-oriented economic climate. This suggests an emphasis on effective financial management, economic planning, and fiscal stability.

2. **Enhancing National Security**: The considerable funding allocated to the Ministry of Defence reflects a strategic priority on strengthening national security and defense infrastructure. This investment highlights the government’s dedication to improving security measures and defense readiness.

3. **Advancing Infrastructure Development**: The significant financial support for the Ministry of Road Transport and Highways and the Ministry of Railways demonstrates a strategic emphasis on improving transportation infrastructure. This focus aims to enhance connectivity, facilitate economic activities, and support overall infrastructure development.

4. **Promoting Balanced Development**: The overall allocation of funds indicates a well-rounded approach that addresses economic stability, national security, and infrastructure enhancement. This strategy is crucial for ensuring comprehensive national development and long-term stability.
"""

